//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 03:48:00 PM CDT 
//


package com.fedex.ws.rate.v21;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Electronic Trade document references used with the ETD special service.
 * 
 * <p>Java class for EtdDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EtdDetail"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Confirmation" type="{http://fedex.com/ws/rate/v21}EtdConfirmationType" minOccurs="0"/&gt;
 *         &lt;element name="Attributes" type="{http://fedex.com/ws/rate/v21}EtdAttributeType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="RequestedDocumentCopies" type="{http://fedex.com/ws/rate/v21}RequestedShippingDocumentType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="DocumentReferences" type="{http://fedex.com/ws/rate/v21}UploadDocumentReferenceDetail" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EtdDetail", propOrder = {
    "confirmation",
    "attributes",
    "requestedDocumentCopies",
    "documentReferences"
})
public class EtdDetail {

    @XmlElement(name = "Confirmation")
    @XmlSchemaType(name = "string")
    protected EtdConfirmationType confirmation;
    @XmlElement(name = "Attributes")
    @XmlSchemaType(name = "string")
    protected List<EtdAttributeType> attributes;
    @XmlElement(name = "RequestedDocumentCopies")
    @XmlSchemaType(name = "string")
    protected List<RequestedShippingDocumentType> requestedDocumentCopies;
    @XmlElement(name = "DocumentReferences")
    protected List<UploadDocumentReferenceDetail> documentReferences;

    /**
     * Gets the value of the confirmation property.
     * 
     * @return
     *     possible object is
     *     {@link EtdConfirmationType }
     *     
     */
    public EtdConfirmationType getConfirmation() {
        return confirmation;
    }

    /**
     * Sets the value of the confirmation property.
     * 
     * @param value
     *     allowed object is
     *     {@link EtdConfirmationType }
     *     
     */
    public void setConfirmation(EtdConfirmationType value) {
        this.confirmation = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EtdAttributeType }
     * 
     * 
     */
    public List<EtdAttributeType> getAttributes() {
        if (attributes == null) {
            attributes = new ArrayList<EtdAttributeType>();
        }
        return this.attributes;
    }

    /**
     * Gets the value of the requestedDocumentCopies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestedDocumentCopies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestedDocumentCopies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequestedShippingDocumentType }
     * 
     * 
     */
    public List<RequestedShippingDocumentType> getRequestedDocumentCopies() {
        if (requestedDocumentCopies == null) {
            requestedDocumentCopies = new ArrayList<RequestedShippingDocumentType>();
        }
        return this.requestedDocumentCopies;
    }

    /**
     * Gets the value of the documentReferences property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentReferences property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentReferences().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UploadDocumentReferenceDetail }
     * 
     * 
     */
    public List<UploadDocumentReferenceDetail> getDocumentReferences() {
        if (documentReferences == null) {
            documentReferences = new ArrayList<UploadDocumentReferenceDetail>();
        }
        return this.documentReferences;
    }

}
