//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 03:48:00 PM CDT 
//


package com.fedex.ws.rate.v21;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LabelFormatType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LabelFormatType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="COMMON2D"/&gt;
 *     &lt;enumeration value="ERROR"/&gt;
 *     &lt;enumeration value="FEDEX_FREIGHT_STRAIGHT_BILL_OF_LADING"/&gt;
 *     &lt;enumeration value="LABEL_DATA_ONLY"/&gt;
 *     &lt;enumeration value="MAILROOM"/&gt;
 *     &lt;enumeration value="NO_LABEL"/&gt;
 *     &lt;enumeration value="OPERATIONAL_LABEL"/&gt;
 *     &lt;enumeration value="PRE_COMMON2D"/&gt;
 *     &lt;enumeration value="VICS_BILL_OF_LADING"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LabelFormatType")
@XmlEnum
public enum LabelFormatType {

    @XmlEnumValue("COMMON2D")
    COMMON_2_D("COMMON2D"),
    ERROR("ERROR"),
    FEDEX_FREIGHT_STRAIGHT_BILL_OF_LADING("FEDEX_FREIGHT_STRAIGHT_BILL_OF_LADING"),
    LABEL_DATA_ONLY("LABEL_DATA_ONLY"),
    MAILROOM("MAILROOM"),
    NO_LABEL("NO_LABEL"),
    OPERATIONAL_LABEL("OPERATIONAL_LABEL"),
    @XmlEnumValue("PRE_COMMON2D")
    PRE_COMMON_2_D("PRE_COMMON2D"),
    VICS_BILL_OF_LADING("VICS_BILL_OF_LADING");
    private final String value;

    LabelFormatType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LabelFormatType fromValue(String v) {
        for (LabelFormatType c: LabelFormatType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
