//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 03:48:00 PM CDT 
//


package com.fedex.ws.rate.v21;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies details needed to generate any label artifacts required due to regulatory requirements.
 * 
 * <p>Java class for RegulatoryLabelContentDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegulatoryLabelContentDetail"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Type" type="{http://fedex.com/ws/rate/v21}RegulatoryLabelType" minOccurs="0"/&gt;
 *         &lt;element name="GenerationOptions" type="{http://fedex.com/ws/rate/v21}CustomerSpecifiedLabelGenerationOptionType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegulatoryLabelContentDetail", propOrder = {
    "type",
    "generationOptions"
})
public class RegulatoryLabelContentDetail {

    @XmlElement(name = "Type")
    @XmlSchemaType(name = "string")
    protected RegulatoryLabelType type;
    @XmlElement(name = "GenerationOptions")
    @XmlSchemaType(name = "string")
    protected List<CustomerSpecifiedLabelGenerationOptionType> generationOptions;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link RegulatoryLabelType }
     *     
     */
    public RegulatoryLabelType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegulatoryLabelType }
     *     
     */
    public void setType(RegulatoryLabelType value) {
        this.type = value;
    }

    /**
     * Gets the value of the generationOptions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the generationOptions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenerationOptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomerSpecifiedLabelGenerationOptionType }
     * 
     * 
     */
    public List<CustomerSpecifiedLabelGenerationOptionType> getGenerationOptions() {
        if (generationOptions == null) {
            generationOptions = new ArrayList<CustomerSpecifiedLabelGenerationOptionType>();
        }
        return this.generationOptions;
    }

}
