//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 03:48:00 PM CDT 
//


package com.fedex.ws.rate.v21;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RestrictionsAndPrivilegesPolicyDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RestrictionsAndPrivilegesPolicyDetail"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ExceptionType" type="{http://fedex.com/ws/rate/v21}RestrictionsAndPrivilegesPolicyExceptionType" minOccurs="0"/&gt;
 *         &lt;element name="PolicyGridManifests" type="{http://fedex.com/ws/rate/v21}PolicyGridManifest" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RestrictionsAndPrivilegesPolicyDetail", propOrder = {
    "exceptionType",
    "policyGridManifests"
})
public class RestrictionsAndPrivilegesPolicyDetail {

    @XmlElement(name = "ExceptionType")
    @XmlSchemaType(name = "string")
    protected RestrictionsAndPrivilegesPolicyExceptionType exceptionType;
    @XmlElement(name = "PolicyGridManifests")
    protected List<PolicyGridManifest> policyGridManifests;

    /**
     * Gets the value of the exceptionType property.
     * 
     * @return
     *     possible object is
     *     {@link RestrictionsAndPrivilegesPolicyExceptionType }
     *     
     */
    public RestrictionsAndPrivilegesPolicyExceptionType getExceptionType() {
        return exceptionType;
    }

    /**
     * Sets the value of the exceptionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestrictionsAndPrivilegesPolicyExceptionType }
     *     
     */
    public void setExceptionType(RestrictionsAndPrivilegesPolicyExceptionType value) {
        this.exceptionType = value;
    }

    /**
     * Gets the value of the policyGridManifests property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the policyGridManifests property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolicyGridManifests().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PolicyGridManifest }
     * 
     * 
     */
    public List<PolicyGridManifest> getPolicyGridManifests() {
        if (policyGridManifests == null) {
            policyGridManifests = new ArrayList<PolicyGridManifest>();
        }
        return this.policyGridManifests;
    }

}
